import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import AuthModalBridge from "@/components/AuthModalBridge";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Client-only modal state is handled in a client wrapper
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
        style={{
          backgroundImage:
            "radial-gradient(ellipse at top, rgba(232,181,126,0.08), transparent 60%), radial-gradient(ellipse at bottom, rgba(243,201,139,0.06), transparent 60%)",
        }}
      >
        <Navbar />
        <main className="mx-auto max-w-6xl px-4">{children}</main>
        <Footer />
        {/* Global modal mount via a client wrapper */}
        <AuthModalBridge />
      </body>
    </html>
  );
}

// Client bridge moved to its own file to avoid importing client hooks in a server file
